---

- name: Setup raspycar
  hosts: raspycar
  gather_facts: no
  tasks:
    - name: Instal uv4l
      become: yes
      tags: [video]
      block:
        - name: Add apt-key
          apt_key:
            url: http://www.linux-projects.org/listing/uv4l_repo/lpkey.asc
            state: present

        - name: Add apt repository
          apt_repository:
            repo: "deb http://www.linux-projects.org/listing/uv4l_repo/raspbian/stretch stretch main"
            state: present
            filename: uv4l
            update_cache: yes

        - name: Install packages
          apt:
            name:
              - uv4l
              - uv4l-server
              - uv4l-raspicam
              - uv4l-raspicam-extras
            state: present

        - name: Edit config
          block:
            - name: Setup width
              lineinfile:
                state: present
                path: "{{ video_conf_path }}"
                regexp: ^width
                line: "width = {{ video_width }}"

            - name: Setup height
              lineinfile:
                state: present
                path: "{{ video_conf_path }}"
                regexp: ^height
                line: "height = {{ video_height }}"

            - name: Setup framerate
              lineinfile:
                state: present
                path: "{{ video_conf_path }}"
                regexp: ^framerate
                line: "framerate = {{ video_framerate }}"

        - name: Start service
          service:
            name: uv4l_raspicam
            enabled: yes
            state: restarted
        
    - name: Install Python 3 and dependencies
      tags: [python]
      become: yes
      apt:
        state: present
        name:
          - python3
          - python3-pip
          - python3-venv

    - name: Update sources
      tags: [app]
      block:
        - name: Install git
          become: yes
          apt:
            state: present
            name: git

        - name: Update repo sources
          git:
            repo: https://github.com/raspycar/server.git
            dest: /home/pi/raspycar-server
            version: "{{raspycar_version}}"

    - name: Install Poetry
      tags: [python]
      block:
        - name: Download installation script
          get_url:
            url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
            dest: /tmp/get-poetry.py
        - name: Install
          command: python3 /tmp/get-poetry.py -y

    - name: Install pip
      tags: [python]
      block:
        - name: Download installation script
          get_url:
            url: https://bootstrap.pypa.io/get-pip.py
            dest: /tmp/get-pip.py
        - name: Install
          command: /home/pi/.poetry/bin/poetry run python /tmp/get-pip.py
          args:
            chdir: /home/pi/raspycar-server

    - name: Install app
      tags: [app]
      block:
        - name: Write configuration file
          template:
            src: server_config.j2
            dest: /home/pi/raspycar-server/.env
        - name: Install dependencies
          command: /home/pi/.poetry/bin/poetry install --no-dev
          args:
            chdir: /home/pi/raspycar-server

    - name: Setup supervisor
      become: yes
      tags: [supervisor]
      block:
        - name: Install package
          apt:
            name: supervisor
            state: present
        - name: Start service
          service:
            name: supervisor
            enabled: yes
            state: restarted

    - name: Write supervisor config
      become: yes
      tags: [app]
      template:
        src: supervisor.j2
        dest: /etc/supervisor/conf.d/raspycar.conf

    - name: Restart supervisor
      become: yes
      tags:
        - supervisor
        - app
      supervisorctl:
        name: raspycar:uvicorn-0
        state: restarted