---

- name: Setup raspycar
  hosts: raspycar
  gather_facts: no
  tasks:
    - name: Instal uv4l
      become: yes
      tags: [video]
      block:
        - name: Add apt-key
          apt_key:
            url: http://www.linux-projects.org/listing/uv4l_repo/lpkey.asc
            state: present

        - name: Add apt repository
          apt_repository:
            repo: "deb http://www.linux-projects.org/listing/uv4l_repo/raspbian/stretch stretch main"
            state: present
            filename: uv4l
            update_cache: yes

        - name: Install packages
          apt:
            name:
              - uv4l
              - uv4l-server
              - uv4l-raspicam
              - uv4l-raspicam-extras
            state: present

        - name: Edit config
          block:
            - name: Setup width
              lineinfile:
                state: present
                path: "{{ video_conf_path }}"
                regexp: ^width
                line: "width = {{ video_width }}"

            - name: Setup height
              lineinfile:
                state: present
                path: "{{ video_conf_path }}"
                regexp: ^height
                line: "height = {{ video_height }}"

            - name: Setup framerate
              lineinfile:
                state: present
                path: "{{ video_conf_path }}"
                regexp: ^framerate
                line: "framerate = {{ video_framerate }}"

        - name: Start service
          service:
            name: uv4l_raspicam
            enabled: yes
            state: restarted
